Add post action.
Generally, the builders.sh script does a lot of things right
after the images have been bitbaked. The post command does
that:
* compresses and converts images,
* creates MD5SUMS.txt file,
* creates build_config.json, and
* creates post_build_lava_parameters.

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>

diff --git a/loeb b/loeb
--- a/loeb
+++ b/loeb
@@ -658,12 +658,145 @@ loeb_justbuild()
   loeb env bitbake ${targets}
 }
 
+loeb_post()
+{
+  #set -xeu
+  DEPLOY_DIR_IMAGE=$(bitbake -e | grep "^DEPLOY_DIR_IMAGE="| cut -d'=' -f2 | tr -d '"')
+
+  # Prepare files to publish
+  rm -f ${DEPLOY_DIR_IMAGE}/*.txt
+  find ${DEPLOY_DIR_IMAGE} -type l -delete
+  [ -e /srv/oe/source-manifest.xml ] && mv -v /srv/oe/source-manifest.xml ${DEPLOY_DIR_IMAGE}
+  [ -e /srv/oe/pinned-manifest.xml ] && mv -v /srv/oe/pinned-manifest.xml ${DEPLOY_DIR_IMAGE}
+  [ -e /srv/oe/pinned-manifest.xml ] && cat ${DEPLOY_DIR_IMAGE}/pinned-manifest.xml
+
+  # FIXME: IMAGE_FSTYPES_remove doesn't work
+  rm -fv ${DEPLOY_DIR_IMAGE}/*.rootfs.ext4 \
+        ${DEPLOY_DIR_IMAGE}/*.rootfs.iso \
+        ${DEPLOY_DIR_IMAGE}/*.rootfs.wic* \
+        ${DEPLOY_DIR_IMAGE}/*.iso \
+        ${DEPLOY_DIR_IMAGE}/*.stimg
+
+  # FIXME: Sparse and converted images here, until it gets done by OE
+  case "${MACHINE}" in
+    juno)
+      ;;
+    intel-core2-32)
+      for rootfs in ${DEPLOY_DIR_IMAGE}/*.hddimg; do
+        [ -e ${rootfs} ] && pxz -v ${rootfs}
+      done
+      ;;
+    *)
+      for rootfs in ${DEPLOY_DIR_IMAGE}/*.rootfs.ext4.gz; do
+        gunzip -k ${rootfs}
+        sudo ext2simg -v ${rootfs%.gz} ${rootfs%.ext4.gz}.img
+        rm -f ${rootfs%.gz}
+        gzip -9v ${rootfs%.ext4.gz}.img
+      done
+      ;;
+  esac
+
+  # Create MD5SUMS file
+  find ${DEPLOY_DIR_IMAGE} -type f | xargs md5sum > MD5SUMS.txt
+  sed -i "s|${DEPLOY_DIR_IMAGE}/||" MD5SUMS.txt
+  cat MD5SUMS.txt
+  mv MD5SUMS.txt ${DEPLOY_DIR_IMAGE}
+
+  GCCVERSION=$(bitbake -e | grep "^GCCVERSION="| cut -d'=' -f2 | tr -d '"')
+  TARGET_SYS=$(bitbake -e | grep "^TARGET_SYS="| cut -d'=' -f2 | tr -d '"')
+  TUNE_FEATURES=$(bitbake -e | grep "^TUNE_FEATURES="| cut -d'=' -f2 | tr -d '"')
+  STAGING_KERNEL_DIR=$(bitbake -e | grep "^STAGING_KERNEL_DIR="| cut -d'=' -f2 | tr -d '"')
+
+  # lkft-metadata class generates metadata file, which can be sourced
+  for recipe in kselftests-mainline kselftests-next ltp libhugetlbfs; do
+    md=lkftmetadata/packages/*/${recipe}/metadata
+    if [ -e ${md} ]; then
+      source lkftmetadata/packages/*/${recipe}/metadata
+    else
+      echo "WARNING: Not found: ${md}"
+    fi
+  done
+
+  BOOT_IMG=$(find ${DEPLOY_DIR_IMAGE} -type f -name "boot-*-${MACHINE}-*-${BUILD_NUMBER}*.img" | sort | xargs -r basename)
+  KERNEL_IMG=$(find ${DEPLOY_DIR_IMAGE} -type f -name "*Image-*-${MACHINE}-*-${BUILD_NUMBER}.bin" | xargs -r basename)
+  ROOTFS_IMG=$(find ${DEPLOY_DIR_IMAGE} -type f -name "rpb-console-image-lkft-${MACHINE}-*-${BUILD_NUMBER}.rootfs.img.gz" | xargs -r basename)
+  ROOTFS_EXT4=$(find ${DEPLOY_DIR_IMAGE} -type f -name "rpb-console-image-lkft-${MACHINE}-*-${BUILD_NUMBER}.rootfs.ext4.gz" | xargs -r basename)
+  ROOTFS_TARXZ_IMG=$(find ${DEPLOY_DIR_IMAGE} -type f -name "rpb-console-image-lkft-${MACHINE}-*-${BUILD_NUMBER}.rootfs.tar.xz" | xargs -r basename)
+  HDD_IMG=$(find ${DEPLOY_DIR_IMAGE} -type f -name "rpb-console-image-lkft-${MACHINE}-*-${BUILD_NUMBER}.hddimg.xz" | xargs -r basename)
+  case "${MACHINE}" in
+    am57xx-evm)
+      # QEMU arm 32bit needs the zImage file, not the uImage file.
+      # KERNEL_IMG is not used for the real hardware itself.
+      KERNEL_IMG=$(find ${DEPLOY_DIR_IMAGE} -type f -name "zImage-*-${MACHINE}-*-${BUILD_NUMBER}.bin" | xargs -r basename)
+      ;;
+    juno)
+      DTB_IMG=$(find ${DEPLOY_DIR_IMAGE} -type f -name "*Image-*-${MACHINE}-r2-*-${BUILD_NUMBER}.dtb" | xargs -r basename)
+      ;;
+  esac
+
+  cat > ${DEPLOY_DIR_IMAGE}/build_config.json <<EOF
+{
+  "kernel_repo" : "${KERNEL_REPO}",
+  "kernel_commit_id" : "${SRCREV_kernel}",
+  "make_kernelversion" : "${MAKE_KERNELVERSION}",
+  "kernel_branch" : "${KERNEL_BRANCH}",
+  "kernel_describe" : "${KERNEL_DESCRIBE}",
+  "kselftest_mainline_url" : "${KSELFTESTS_MAINLINE_URL}",
+  "kselftest_mainline_version" : "${KSELFTESTS_MAINLINE_VERSION}",
+  "kselftest_next_url" : "${KSELFTESTS_NEXT_URL}",
+  "kselftest_next_version" : "${KSELFTESTS_NEXT_VERSION}",
+  "ltp_url" : "${LTP_URL}",
+  "ltp_version" : "${LTP_VERSION}",
+  "ltp_revision" : "${LTP_REVISION}",
+  "libhugetlbfs_url" : "${LIBHUGETLBFS_URL}",
+  "libhugetlbfs_version" : "${LIBHUGETLBFS_VERSION}",
+  "libhugetlbfs_revision" : "${LIBHUGETLBFS_REVISION}",
+  "build_arch" : "${TUNE_FEATURES}",
+  "compiler" : "${TARGET_SYS} ${GCCVERSION}",
+  "build_location" : "${BASE_URL}/${PUB_DEST}"
+}
+EOF
+echo "${DEPLOY_DIR_IMAGE}/build_config.json:"
+cat ${DEPLOY_DIR_IMAGE}/build_config.json
+
+  cat << EOF > ${WORKSPACE}/post_build_lava_parameters
+DEPLOY_DIR_IMAGE=${DEPLOY_DIR_IMAGE}
+BASE_URL=${BASE_URL}
+BOOT_URL=${BASE_URL}/${PUB_DEST}/${BOOT_IMG}
+SYSTEM_URL=${BASE_URL}/${PUB_DEST}/${ROOTFS_IMG}
+KERNEL_URL=${BASE_URL}/${PUB_DEST}/${KERNEL_IMG}
+DTB_URL=${BASE_URL}/${PUB_DEST}/${DTB_IMG}
+RECOVERY_IMAGE_URL=${BASE_URL}/${PUB_DEST}/juno-oe-uboot.zip
+NFSROOTFS_URL=${BASE_URL}/${PUB_DEST}/${ROOTFS_TARXZ_IMG}
+EXT4_IMAGE_URL=${BASE_URL}/${PUB_DEST}/${ROOTFS_EXT4}
+HDD_URL=${BASE_URL}/${PUB_DEST}/${HDD_IMG}
+KERNEL_COMMIT=${SRCREV_kernel}
+KERNEL_CONFIG_URL=${BASE_URL}/${PUB_DEST}/config
+KERNEL_DEFCONFIG_URL=${BASE_URL}/${PUB_DEST}/defconfig
+KSELFTESTS_MAINLINE_URL=${KSELFTESTS_MAINLINE_URL}
+KSELFTESTS_MAINLINE_VERSION=${KSELFTESTS_MAINLINE_VERSION}
+KSELFTESTS_NEXT_URL=${KSELFTESTS_NEXT_URL}
+KSELFTESTS_NEXT_VERSION=${KSELFTESTS_NEXT_VERSION}
+LTP_URL=${LTP_URL}
+LTP_VERSION=${LTP_VERSION}
+LTP_REVISION=${LTP_REVISION}
+LIBHUGETLBFS_URL=${LIBHUGETLBFS_URL}
+LIBHUGETLBFS_VERSION=${LIBHUGETLBFS_VERSION}
+LIBHUGETLBFS_REVISION=${LIBHUGETLBFS_REVISION}
+MAKE_KERNELVERSION=${MAKE_KERNELVERSION}
+TOOLCHAIN="${TARGET_SYS} ${GCCVERSION}"
+EOF
+
+  echo "${WORKSPACE}/post_build_lava_parameters:"
+  cat "${WORKSPACE}/post_build_lava_parameters"
+}
+
 # START HERE
 BASE_DIR=$(get_repo_base_dir)
 BASE_DIR=${BASE_DIR:-.}
 CONFIG_FILE="${BASE_DIR}/.loeb.config"
 BUILD_DIR=${BUILD_DIR:-build}
-BUILD_NUMBER=${BUILD_NUMBER:-1337}
+export BUILD_NUMBER=${BUILD_NUMBER:-1337}
 SILENT=FALSE
 
 if [ $# -lt 1 ]; then
@@ -708,6 +841,9 @@ case ${action} in
     ;;
   justbuild)
     loeb_justbuild $*
+    ;;
+  post)
+    loeb_post $*
     ;;
   reset)
     loeb_reset $*
